
skillMetadata:
  sections:
    - name: TuneIn radio
      fields:
        - type: label
          label: This skill uses TuneIn to give you access to thousands of radio channels. Enter below aliases for some of the channels. 
    - name: Channel alias
      fields:
        - name: name1
          type: text
          label: Official channel name
          value: ""
        - name: alias1
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name2
          type: text
          label: Official channel name
          value: ""
        - name: alias2
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name3
          type: text
          label: Official channel name
          value: ""
        - name: alias3
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name4
          type: text
          label: Official channel name
          value: ""
        - name: alias4
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name5
          type: text
          label: Official channel name
          value: ""
        - name: alias1
          type: text
          label: Channel alias
          value: ""
